name: push container

on:
  push:
    branches: master
  schedule:
    - cron: "30 12 * * 0/3"

jobs:
  main:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    steps:
      -
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bbsdocker/imagedreambbs:latest,bbsdocker/imagedreambbs:${{ steps.date.outputs.date }}
            build-args:
              DREAMBBS_GIT="https://github.com/ccns/dreambbs.git"
              DREAMBBS_SNAP_GIT="https://github.com/ccns/dreambbs_snap.git"

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
