name: build (master)

on:
  workflow_dispatch:
    inputs:
        build_result:
          description: "The build result for the master branch"
          required: true
          default: "failure"

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Forward build result
        run: ${{ github.event.inputs.build_result == 'success' && 'true' || 'false' }}
