name: push container (development branch)

on:
  push:
    branches: master
  schedule:
    - cron: "30 9 * * 2,5"
  workflow_dispatch:
    inputs:
        src_ref:
          description: "The branch/tag for which the dispatch is sent from dreambbs project"
          required: true
          default: "refs/heads/develop"
        src_sha:
          description: "The commit SHA for which the dispatch is sent from dreambbs project"
          required: true
          default: ""

env:
    SRC_SHA: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.src_sha || '' }}
    SRC_REF: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.src_ref || format('refs/heads/{1}', 'develop') }}

jobs:
  main:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-20.04
    steps:
      -
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Getting Commit Information from DreamBBS
        run: |
          SRC_REF_INFO="$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/ccns/dreambbs/branches/$SRC_REF")"
          SRC_BRANCH="$(jq '.name' <<< "$SRC_REF_INFO")"
          if [ -z "$SRC_SHA" ]; then
            SRC_SHA="$(jq -r '.commit.sha' <<< "$SRC_REF_INFO")"
          fi
          echo "SRC_BRANCH=$SRC_BRANCH" >> $GITHUB_ENV
          echo "SRC_SHA=$SRC_SHA" >> $GITHUB_ENV
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            "SRC_BRANCH=${{ env.SRC_BRANCH }}"
            "SRC_SHA=${{ env.SRC_SHA }}"
            "SRC_REF=${{ env.SRC_REF }}"
          tags: |
            ${{ secrets.DOCKERHUB_REPO_OWNER }}/imagedreambbs:develop
            ${{ secrets.DOCKERHUB_REPO_OWNER }}:develop-latest
            ${{ secrets.DOCKERHUB_REPO_OWNER }}:develop-${{ steps.date.outputs.date }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name : Add Notification in bbs-dev in CCNS Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
